# Generated by Django 4.2.7 on 2023-11-03 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_listing_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="current_bid",
        ),
    ]
