# Generated by Django 4.2.7 on 2023-11-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_remove_listing_comment_remove_listing_current_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="active",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="comment",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="comment", to="auctions.comment"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="current_bid",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="bid", to="auctions.bid"
            ),
        ),
    ]
