# Generated by Django 4.2.7 on 2023-11-05 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_listing_active_listing_comment_listing_current_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="current_bid",
        ),
        migrations.AddField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listingBid",
                to="auctions.listing",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listingComment",
                to="auctions.listing",
            ),
        ),
    ]
