# Generated by Django 4.2.7 on 2023-11-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_remove_listing_comment_remove_listing_current_bid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="listing",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
