# Generated by Django 4.2.7 on 2023-11-15 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="post",
            new_name="liked_post",
        ),
    ]
